### ISSUE TITLE
Noise has always the same seed

### ISSUE THREAD

**Issue by BarbaraAlmeida** [processing-js/processing-js#131]
I always get the same pattern, even though I'm applying random numbers to noiseSeed each time mouse is pressed. Even without calling the noiseSeed function the pattern is always the same each time I run the sketch.
It seems that it's not a problem with the sketch, noiseSeed works as expected on Java mode.

Link for more information and code: http://forum.processing.org/two/discussion/8858/does-noiseseed-work-on-javascript-mode#Item_2

**Comment by Pomax** [comment]
Quick fix: use `randomSeed` instead of `noiseSeed`. Looking at https://github.com/processing-js/processing-js/blob/6fb2910cff3bd51db85d1111ad2e01a916107442/src/P5Functions/Math.js#L665 the seed is set correctly, and https://github.com/processing-js/processing-js/blob/6fb2910cff3bd51db85d1111ad2e01a916107442/src/P5Functions/Math.js#L605 should create a new PerlinNoise generator, so it's possible something wonky is going on in the generator itself.

**Comment by BarbaraAlmeida** [comment]
I don't get how to do it with randomSeed.
Anyway, just adding a random number to the noise parameters instead of changing the seed gives enough variety to my example, I guess it's enough in most cases actually.

It was the first thing I've tried, but I've put it inside the cos function by mistake so it didn't work and I had to try the noiseSeed, at least it allowed me to find out that there's something weird with the seed.

I wonder if that does have something to do with the fact that noise doesn't look the same on Java and JavaScript mode.
I don't know how the generator works, I first thought it was constructed on different ways on each language, but if there's something going on inside the generator that makes it always use the same seed it may also make it look different. At least they will never have the same seed even if we set it to a constant, so they won't look the same.

**Comment by Pomax** [comment]
the noise generators are definitely different between Processing and Processing.js - you can't rely on the noise pattern to be the same between the two, only that within the same version of Processing, or Processing.js, a specifically seeded generator will generate the same pattern each time.

**Comment by BarbaraAlmeida** [comment]
Thanks for the clarification.


Replacing noiseSeed(seed) to randomSeed(seed) didn't work. The pattern remains the same on both Java and JavaScript modes.

It worked though, only on Processing.js, when I tried any of these options:

seed = noiseSeed();
noiseSeed(seed);

seed = randomSeed();
noiseSeed(seed);

noiseSeed(randomSeed());

noiseSeed(noiseSeed());


I've noticed that Processing.js reference says that noiseSeed() and randomSeed() returns float (while they return void on Procesing, but I don't understand why it works with these functions and it doesn't work with any other value.
Maybe knowing this helps you understand what is going on.

**Comment by BarbaraAlmeida** [comment]
Actually, only noiseSeed() is enough.
noiseSeed should take a parameter, but the noise generator only use a random seed when noiseSeed() is called without a parameter, otherwise it's always the same seed.

**Comment by Pomax** [comment]
hm. https://github.com/processing-js/processing-js/blob/6fb2910cff3bd51db85d1111ad2e01a916107442/src/P5Functions/Math.js#L665 suggests that `noiseSeed` with an argument should force a new generator to be built on the next call to `noise` over at https://github.com/processing-js/processing-js/blob/6fb2910cff3bd51db85d1111ad2e01a916107442/src/P5Functions/Math.js#L604

Calling it without an argument will set the noiseprofile seed value to `undefined`, leading to `new PerlinNoise(undefined)` as new generator, rather than `new PerlinNoise(somevalue)`, which in https://github.com/processing-js/processing-js/blob/6fb2910cff3bd51db85d1111ad2e01a916107442/src/P5Functions/Math.js#L511 means that we "reseed" the generator we already have without an explicit seed value, rather than building a new generator with a true seed.

The reseeding, thus, clearly works.

Looking at the randomiser the PerlinNoise object actually gets back, by looking at what the generator gives us right after https://github.com/processing-js/processing-js/blob/6fb2910cff3bd51db85d1111ad2e01a916107442/src/P5Functions/Math.js#L511 shows that some test `.intGenerator()` calls have completely different values for different seeds, so that part is still fine. However, the permutation array that is build in the lines after that (the `perm` array) is absolutely not fine: no matter which randomiser goes in, the resulting array is always the same.

Sooo here's the hilarious bit: we're permuting a 256 spot identity array (i.e. an array [0,1,2,3,4,...]) by using the Marsaglia generator's pseudo-random integer stream. As full integers, these sequences are different for each seed. However, that's not how we use them. On https://github.com/processing-js/processing-js/blob/6fb2910cff3bd51db85d1111ad2e01a916107442/src/P5Functions/Math.js#L518 we take a random int, and then only keep the last 2 bytes.

So, you are a hero for finding this bug, and guess which part of Marsaglia numbers are always the same no matter the seeding?

**Comment by BarbaraAlmeida** [comment]
Isn't https://github.com/processing-js/processing-js/blob/6fb2910cff3bd51db85d1111ad2e01a916107442/src/P5Functions/Math.js#L518 keeping the last 8 bytes?
The permutation array seems ok, it picks a random number between 0 and 255.

But you're right, this last 8 bytes are always the same when there'is a seed.

The difference seems to be that, when seed is not undefined, Marsaglia is called with only one parameter.
I think this means that on https://github.com/processing-js/processing-js/blob/6fb2910cff3bd51db85d1111ad2e01a916107442/src/P5Functions/Math.js#L442 i2 will be undefined so w will be always equal to 521288629.

But on https://github.com/processing-js/processing-js/blob/6fb2910cff3bd51db85d1111ad2e01a916107442/src/P5Functions/Math.js#L446 , the part of the number that is generated by w will form the last 16 bytes so the last 8 bytes will be always the same.

Maybe line 511 should be changed to:
var rnd = seed !== undef ? new Marsaglia(something here, seed) : Marsaglia.createRandomized();

Or, on line 518:
 var t = perm[j = (rnd.intGenerator() >>> 16) & 0xFF];

I think with one of these the part of the number that the permutation array picks will actually depends on the seed.


There's one thing that I don't understand. What happens when we don't use noiseSeed()?
I would expect both noiseProfile.seed and noiseProfile.generator to be undefined when we run the sketch so it would behave like when we use noiseSeed() without an argument. But it actually behaves like noiseSeed(parameter).

**Comment by Pomax** [comment]
Hmm, if we don't use noiseSeed at all, noiseProfile.seed and noiseProfile.generator should be undefined, `Marsaglia.createRandomized()` will be called, leading to a `new Marsaglia(s1, s2)` call with both arguments filled in (with s2 being s1/60000) over at https://github.com/processing-js/processing-js/blob/6fb2910cff3bd51db85d1111ad2e01a916107442/src/P5Functions/Math.js#L458, so I would expect that to at least generate a distinct sequence for each sketch reload.

And yes, one option is to ignore the marsaglia number that is services by `w`, although the idea that we can safely take a random number, throw away all but one byte, and end up with a new random number is extremely flawed as well.

I think the best fix is probably to take the same approach that createRandomized takes, in that if we pass in a seed value, we see do something like `Marsaglia(seed, (seed << 16) + (seed >> 16)))` or, to keep it in line with the createRandomized function, `Marsaglia(seed*60000, seed)`.

**Comment by Pomax** [comment]
@BarbaraAlmeida I've pushed up a corrected version with a unit test for unseeded and seeded noise calls, can you verify that this also solves your problem?

**Comment by BarbaraAlmeida** [comment]
NoiseSeed is working as expected with version 1.4.9 for both setting it to a constant or changing it with a random value.

Also, I've tested again and not using noiseSeed was already working, as expected from the code, I don't know why I thought it was the same pattern, sorry.

Thank you for the answers and for fixing it so quickly.

**Comment by Domiii** [comment]
For everyone who is still forced to work on an earlier version (e.g. when programming on Khan Academy programming environment): The fix is to call `noiseSeed` without arguments, but since the grammar checker won't let you do that, you can just do:

`noiseSeed(undefined);`

**Comment by Pomax** [comment]
thanks for adding that - hopefully there's a bug filed against khan academy to upgrade their Pjs to at least the last version that got pushed out?

**Comment by Domiii** [comment]
I filed a report. You can track it [here](https://khanacademy.zendesk.com/hc/en-us/requests/136705).
