### ISSUE TITLE
About time to provide a consistent asynchronous API for loading stuff in both Java and JavaScript mode

### ISSUE THREAD

**Issue by teo1978** [processing-js/processing-js#136]
https://github.com/processing/processing/issues/3075

I guess the Processing and Processing-js teams have to work together at the specs for this

**Comment by Pomax** [comment]
Hmm, not really. Pjs is only concerned about parity (insofar as the technologies allow for this), so if Processing adds a callback mechanism (which would be great), Pjs can be updated to support that syntax in a way that works with the changes that are being put forth on the XHR side, provided someone has the time and will to update Pjs to match.

Also, to clarify something: Pjs has no full time developers on it, it's all "volunteers when they have time" at this point, including myself.

Closing this issue, not because it's unimportant, but because there is no "working together" based on the fact that there is no "Processing-js team". I'll be watching that ticket, and hopefully it's something that ends up landing in Processing.

**Comment by matteosistisette** [comment]
Oh well, I tjought the Processing JS devs would be interested in implementing this as soon as possible, especially because it is far easier in JS than it is in Java (Processing JS is currently kind of shooting itself in the foot renouncing to the async behavior that JS provides natively for free, for the sake of providing seamless drop-in compatibility with Processing). That's why I suggested to "work together", in order to avoid ending up with two different incompatible approaches on the ProcessingJS and Processing sides.

Waiting for Processing to do this and then port that to PJS is actually one way to "work together" :)

I would have hoped for the other way around to happen, since Processing evolves kind of slowly...

**Comment by matteosistisette** [comment]
Oh well, I tjought the Processing JS devs would be interested in implementing this as soon as possible, especially because it is far easier in JS than it is in Java (Processing JS is currently kind of shooting itself in the foot renouncing to the async behavior that JS provides natively for free, for the sake of providing seamless drop-in compatibility with Processing). That's why I suggested to "work together", in order to avoid ending up with two different incompatible approaches on the ProcessingJS and Processing sides.

Waiting for Processing to do this and then port that to PJS is actually one way to "work together" :)

I would have hoped for the other way around to happen, since Processing evolves kind of slowly...

**Comment by teo1978** [comment]
Oh well, I tjought the Processing JS devs would be interested in implementing this as soon as possible, especially because it is far easier in JS than it is in Java (Processing JS is currently kind of shooting itself in the foot renouncing to the async behavior that JS provides natively for free, for the sake of providing seamless drop-in compatibility with Processing). That's why I suggested to "work together", in order to avoid ending up with two different incompatible approaches on the ProcessingJS and Processing sides.

Waiting for Processing to do this and then port that to PJS is actually one way to "work together" :)

I would have hoped for the other way around to happen, since Processing evolves kind of slowly...

**Comment by Pomax** [comment]
the problem there is there are no "Pjs devs". Everyone's moved on, I'm the caretaker and will add in things every now and then if it's really broken, but outside of that Processing.js currently depend on patches written by volunteers who need specific bits of Pjs to behave properly wrt Processing proper.

**Comment by GoToLoop** [comment]
> ... and will add in things every now and then if it's really broken, ...

So we can't contribute w/ minor issues & enhancements. Only serious stuff?

**Comment by Pomax** [comment]
you totall can!

in fact, you are more than welcome to: if you're going to invest your personal time to write a patch to unbreak Pjs, I will be extremely happy to help get that landed. But, in terms of them time I have to write code for Processing, I don't really have any time beyond also just fixing small things when I run into them in the same way. Big rewrites require dedicated stretches of time, which my job and side projects rarely allow for.
