### ISSUE TITLE
Canvas performance degrades when focused

### ISSUE THREAD

**Issue by nicknikolov** [processing-js/processing-js#138]
Hi,
I'm experiencing this bug described here:
http://stackoverflow.com/questions/6194791/focusing-on-the-canvas-element-degrades-performance-of-processing-js-page

In my case I am quite confident that my HTML is well formatted. It's such a weird bug that I'm not really sure what to do and how to debug. Any help is very appreciated.
It's my uni project so the whole code is here:
https://github.com/groupnoto/semicolon/

Thanks

**Comment by Pomax** [comment]
I can strongly recommend doing a reduction pass first, to make sure you have the minimal amount of code that still exhibits the problem, so that we can figure out what's going on together: If you remove the codemirror etc. bits and simply load your sketch straight up, do you still see this slowdown when you select the canvas?

**Comment by Pomax** [comment]
closing for now
