### ISSUE TITLE
missing parseXML() function

### ISSUE THREAD

**Issue by teo1978** [processing-js/processing-js#151]
https://processing.org/reference/parseXML_.html

Related: https://github.com/processing-js/processing-js/issues/150

**Comment by Pomax** [comment]
Added in PR https://github.com/processing-js/processing-js/pull/156 by hooking into `XMLelement.parse` (with functor binding in the java parser so it's recognised as Processing API rather than user function)

**Comment by teo1978** [comment]
By the way, don't forget that once parseXML() is available, XML's constructor should no longer take a xml code string as an argument... nor a filename for that matter.
In Processing, the only XML constructor that takes a String argument expects it to be a node name. 
http://processing.org/reference/javadoc/core/
And it's not just a matter of "this should be done this way because Processing does it this way", it's actually better.

**Comment by GoToLoop** [comment]
IMO, that's narrow-minded! Look at the many XML constructors available:
https://github.com/processing/processing/blob/master/core/src/processing/data/XML.java

* It's true they're mostly marked @nowebref. But all of the constructors are `public`!
* Those belong to the vast "undocument" feature group.
* There are many reasons why they're hidden (censored).
* But mostly are merely to avoid littering the API reference w/ so many options.
* Or b/c they're more complex/specialized features.
* A very few is due to deprecation or uncertainty for their permanence.
* But being even stricter than P5 makes transpilation even less successful in case those hidden features are used!

**Comment by teo1978** [comment]
What is narrowminded?
What do you mean by "undocumented"? They are all documented at the Javadoc page, which is linked from the Processing reference page.

Anyway, none of those constructors (neither the "censored" ones nor the only one "advertized" in the Processing reference) take a string of xml code as a parameter, and for a good reason: there's XML.parse() and parseXML() for that.

I don't understand whether you are arguing in favour of against removing XML(String xmlcode) constructor.

I don't get this:
> But being even stricter than P5 makes transpilation even less successful in case those hidden features are actually found out & used!

Why do you mention PJS is  being stricter than P5? PJS is currently being less strict (it's allowing a constructor that doesn't exist in P5, perhaps it existed at some point, and it was removed for good), and I'm talking about making it exactly as strict as, not more nor less. (except for the fact that P5's XML has constructors that take File and InputStream objects, but those things don't even exist in JS, do they?)
I don't know what transpilation is and whether it is a good or bad thing to make it less succesful.

**Comment by GoToLoop** [comment]
> ... none of those constructors take a string of xml code as a parameter,

Well, so what is constructor for? `public XML(String name) {`
https://github.com/processing/processing/blob/master/core/src/processing/data/XML.java#L215

**Comment by GoToLoop** [comment]
> I don't know what transpilation is...

* https://en.wikipedia.org/wiki/Transpile
* https://en.wiktionary.org/wiki/transpile

**Comment by teo1978** [comment]
> Well, so what is this constructor for? public XML(String name) {

Quoting its documentation at http://processing.org/reference/javadoc/core/processing/data/XML.html#XML(java.lang.String)
> public XML(java.lang.String name)
> Parameters:
> name - creates a node **with this name**

**Comment by teo1978** [comment]
In Processing:
```
new XML("root"); // produces a <root> node
```
and it's the only use of the constructor with that signature. Which is good, because if you want to build an XML from a string of xml code you use parseXML() and if you want to load it from a file/url you use loadXML().

In ProcessingJS:
```
new XML("<root>"); // produces a <root> node
new XML("somefile.xml"); // load a xml document from somefile.xml
new XML("http://somefile.php"); // tries to interpret "http://somefile.php" as xml code and gives error (EPIC FAIL)
```
I'm not even sure whether ProcessingJS takes ```new XML("nodename")``` (which would be the only legitimate constructor), but it tries to "guess" whether the argument is a filename/url or a chunk of xml code, which it shouldn't do in the first place and which it does with poor criteria.

Completely incompatible with Processing's API.

Plus, even worse, it does the same with loadXML() (because it's basically a wrapper around new XML()), but that's tracked in another bug. (which I had reported years ago back in lighthouse and wasn't even migrated, so I reported again a few days ago).

**Comment by GoToLoop** [comment]
> Processing's XML API did change over time...

* PJS framework mostly matches the old Processing 1.5.1's API for now.
* Since signature **XML(String)* has been re-purposed to mean something else, I agree that the "parse" constructor should move to its own dedicated parse method.

**Comment by teo1978** [comment]
>PJS framework mostly matches the old Processing 1.5.1's API for now.

Yeah, about time to update it a little bit;)

**Comment by Pomax** [comment]
bear in mind that the 2.0 and 2.1 APIs were pretty much "the same" as 1.5 but with "XML" instead of "XMLElement" - Processing stopped versioning itself in lockstep with changes to the API that are backward incompatible (not sure why) so what was the 2.x API last year no longer matches what the 2.x API is this year =)

I'll see about updating the XML object to the current constructor, but that shouldn't hold up landing the XML.parseXML function. If it works the way it should, let's land it and simply move on to the next bit to improve until the XML API is back to where it needs to be.

Far as I can tell this patch does what it needs to do, @teo1978 can you confirm that's the case? If so I'll merge it in and move on to fixing up the constructor.

**Comment by Pomax** [comment]
filed https://github.com/processing-js/processing-js/issues/157 as followup
