### ISSUE TITLE
keyPressed()/keyReleased() events are not triggered unless the canvas is focused 

### ISSUE THREAD

**Issue by teo1978** [processing-js/processing-js#185]
keyPressed() and keyReleased() are not triggered unless the canvas is focused, which usually means that they won't work until you click on it. I guess that's because processing.js attaches the listeners to the canvas object.
Coming from Processing, one expects a sketch to immediately start responding to key events without having to click on the canvas (which can have side effects if mouseClicked() is defined).

Attaching the event listeners to the html body rather than the canvas may be too aggressive for some cases, as having the sketch react to keystrokes while, for example, the user is typing into a form element in the same page, may not be the desired behavior for all cases.
But the current behavior is very frustrating.

I'd suggest either (or both):

A) have a @pjs directive to decide whether processing.js attaches listeners for key events to the canvas or to the whole document. The default should be the document unless (B) is also implemented
B) have processing.js give focus to the canvas at startup

Actually I'd be in favour of implementing either both or (A) alone, because (B) alone may not be satisfying, as keys will stop working as soon as the user clicks somewhere outside the canvas and she won't know why.

**Comment by Pomax** [comment]
Welcome to the web: this is how things work. Specifically, "a canvas on a page" wrt Processiing.js is identical to "a sketch running on your desktop" for plain Processing: If I click on my text editor, my key events don't go into my running sketch because it does not have focus. The same goes for sketches on a webpage. If you're not "on" the sketch on the webpage, events won't fire on it, and that's a good thing.

If you want immediate focus when the page loads, you can easily add that with a document ready event handler (to effect `document.getElementById('yourcanvas').focus()`), or if you want to live really dangerously, you can write an event redirect from document to canvas (which means you'll get events that your users might not expect your sketch to get, like page navigation key events. Respect those).

I'd recommend using a simple focus request on document load, but that's something that, if you need it, is very little work, and does not deserve a predirective (those are for getting around the limitations of the browser wrt java, and this is not really a limitation, just medium-specific behaviour that you can easily work around yourself).

**Comment by teo1978** [comment]
> Specifically, "a canvas on a page" wrt Processiing.js is identical to "a sketch running on your desktop" for plain Processing

With an important difference: when you launch a sketch on your desktop, its window is given focus at the moment of launching it, and it gets keystrokes from the beginning. When you open a webpage with a sketch, the sketch is not focused immediately.

> (... Having Pjs assign focus to a sketch on a page where there are multiple sketches, or the sketch is not the main thing on the page, or a combination of those (e.g. http://pomax.github.io/bezierinfo) would be amazingy wrong)
> Remember that Pjs is not Processing's "JavaScript mode", (...) you should totally request that feature on the JavaScript mode github repository.

Indeed, you are right =)

**Comment by Pomax** [comment]
Slight sidenote on "its window is given focus at the moment of launching it": I do a lot of multitasking between the PDE and sublime text, quite often if I hit "play" in the PDE and then go to sublime to keep writing my docs while the sketch fires up, that won't actually happen. It only gets focus if the PDE was focussed when the JFrame is created (far as I know a `focus()` call only succeeds if the master JVM runner is registered as currently focussed by the OS)
