### ISSUE TITLE
how to start the draw loop?

### ISSUE THREAD

**Issue by freder** [processing-js/processing-js#193]
hi,

I would like to use processing.js in with plain javascript. — having read [http://processingjs.org/articles/jsQuickStart.html#javascriptonlyprocessingcode](http://processingjs.org/articles/jsQuickStart.html#javascriptonlyprocessingcode), I do:

```javascript
function sketch(p) {
	// [...]

	p.setup = function() {
		console.log('setup');
		w = 600;
		h = w;
		p.size(w, h/*, p.OPENGL*/);
		p.frameRate(30);
		// [...]
	}

	p.draw = function() {
		console.log('draw');
		// [...]
	}
}

$(document).ready(function() {
	var canvas = document.getElementById('logo');
	var p = new Processing(canvas, sketch);
});
```

`setup()` is called, however `draw()` isn't. is there anything I need to do to get the draw loop going?

I tried adding `p.loop()` in a couple of places, without success.

`processing.js 1.4.15`

**Comment by GoToLoop** [comment]
* There are some posts already reporting that pjs w/ raw JS stopped working.
* Actually I'm impressed that it could get as far as **setup()**. I doubt it though!
* AFAIK, raw JS was removed since v1.4.9. So we gotta stick w/ v1.4.8 at most for it!
* Here's an online raw JS sketch w/ v1.4.7: https://jsfiddle.net/c0j4Lok8/6/
* We can grab v1.4.8 here: http://cdnjs.cloudflare.com/ajax/libs/processing.js/1.4.8/processing.min.js

**Comment by Pomax** [comment]
To add to @GoToLoop correct answer, as of Pjs 1.4.9 the "pure JS" way to use Pjs has been removed, as there are far better graphics libraries out there if you're going to work purely in JS. Pjs has since been purely for running true Processing source code. You can use 1.4.8 or older, but I would strongly recommend using a better pure JS graphics library instead (like paper.js, rafael, d3, etc).

**Comment by GoToLoop** [comment]
But I still wonder why remove a gr8 feature w/o even discussing about it?
Was it so hard to keep it around? More so that after it got removed lotsa folks missed it?
Step by step pjs is losing more of its luster and p5.js is taking its place completely.  =(
