### ISSUE TITLE
state explicitly that "pure JS" is not supported in docs

### ISSUE THREAD

**Issue by LujunWeng** [processing-js/processing-js#240]
According to #193 , as of 1.4.9, the "pure JS" is not supported anymore. I strongly hope you can state that explicitly in your [javascript guide](http://processingjs.org/articles/jsQuickStart.html) so that others does not waste time to figure out why `draw` does not work. Also, there should be given some alternatives, for example using 1.4.8 version or other similar libraries.

**Comment by GoToLoop** [comment]
The arbitrary removal of "pure JS" @ version 1.4.9 was a mercy kill for Pjs.  =(
We can't, for example, use TypeScript for Pjs. The CoffeeScript Mode is forever stuck @ version 1.4.8!

**Comment by teo1978** [comment]
The alternative is P5*js.
PJS has been dead for a while. 

And so is Processing(Java) by the way. I mean, still no asynchronous loading API (of images, XML, etc) in 20f***ing16? Come on! And they don't even care about it. It's pretty sad. It was glorious, like 10 years ago, but there's no ongoing effort to maintain it. Not in any sensible direction, anyway.

**Comment by GoToLoop** [comment]
> The alternative is P5*js.
> PJS has been dead for a while.
> And so is Processing(Java) by the way.

Java Mode is still the king of debugging. Writing sketches in JS demands much more discipline than Java.
As we all know, Processing's target public is the artist category w/o much knowledge in programming.
However Khan Academy's Pjs version is even easier, even though it's in JS: http://KhanAcademy.org/cs

Recall that Pjs' main objective is to deploy Java Mode to the web via Java to JS transpilation.
But Pjs is still a full JS graphics library by itself. And it's revolting to lose such feature @ version 1.4.9!  :angry: 

> ... still no asynchronous loading API (of images, XML, etc) ...

All rookies in JS stumble upon JS' asynchronous trap!
It's very unintuitive for something like `img = loadImage("myPic.jpg"); image(img, 0, 0);` to fail. :eyes: 

Nonetheless, both Java Mode & Pjs offer **requestImage()**, which is asynchronous btW:  :smiling_imp: 
https://Processing.org/reference/requestImage_.html
http://ProcessingJS.org/reference/requestImage_/

Besides, Java is 1 of the best asynchronous languages. Java can instantiate threads w/ sharing memory.
It means we can turn anything synchronous to asynchronous. That includes l/O operations of course. :v: 
Take a look at Processing's function **thread()** web reference: https://Processing.org/reference/thread_.html

**Comment by teo1978** [comment]
> Besides, Java is 1 of the best asynchronous languages. Java can instantiate threads w/ sharing memory.

I know, **that's exactly why it's a shame** that Processing still hasn't made the tiniest step towards an asynchronous API. It could *easily* have a complete, elegant, powerful **and** simple asynchronous API for everything. But they don't give a sh** about that. That's sad.

> Nonetheless, both Java Mode & Pjs offer requestImage(), which is asynchronous btW

Yep, I know. **Asynchronous without a callback**. How shitty is that. And that's about all there is about asynchronous in Processing-Java. There was a feature request in Processing's bug tracker asking to add the possibility to provide some sort of callback in requestImage(), which would be straight-forward. Fry and/or Reas rejected it because a complete full-blown consistent and elegant asynchronous API was going to be added to all of Processing in the next release, making that feature request obsolete. That was, I don't know, five years ago? Still hasn't happened. Pathetic.

> Java Mode is still the king of debugging. 
As we all know, Processing's target public is the artist category w/o much knowledge in programming.

Yeah, it's great for learning. **Until** the day comes when you want to **do something real**. 

Then you have **two choices**. Stick with Java, learn and use Java-specific stuff, libraries, etc, but then you are condemn to stay outside of the www, because it's based on Java. (Not to mention all the *"oh shit this is a float, not a double"* or viceversa nightmares you have to deal with, just because the authors of Processing though [and sadly maintain] that it would be more pretty to write "float" than "double" in your code). 

**Or,** you use PJS in order to get your sketches online (that is, to have them exist in the real world and in the present), but then (1) you have to figure out all the subtle things that break when switching between Java and JavaScript modes (which you have to debug in JS because that's where they break if you come from Processing), and (2) when it comes to loading stuff, you either stick to the synchronous shit (where you are in an environment which would be natively and easily asynchronous but shoots on its own foot to emulate the synchronousness of old plain one-thread Java - which it does for a good reason, because it's just meant to be a port of Processing, which in turn *could* have a fully asynchronous API, just a bit less easily, for their implementors not for you, but they don't want to so PJS is forced to emulate *that*), or go asynchronous by writing JS code, but then loose the ability to switch back to Java mode when you need to debug something.

So the only viable choice is **the third one**: ok, you have learnt the basic of programming, now learn another language (or another incompatible variant of Processing, e.g. P5*JS) that you can actually use to do real stuff.

Definitely a **great scenario** for "_the artist category w/o much knowledge in programming_".

Note that this was not like this when Processing was created. **Back then**, doing stuff in Java *was* pretty much doing real stuff. Not being able to "go online" wasn't necessarily a crippling constraint (there was still life outside the web); and also, you actually *could* easily get online, because Java applets weren't obsolete yet (actually, it looked like they were meant to be *the future* of the web). However, things changed; but Processing is stuck in that past.

Ironically, there *is* a place where Processing's Java roots could be a great advanced, and that is **Android**. So Processing's Android mode would have had a great potential. But sadly **they dropped that too**.

> All rookies in JS stumble upon JS' asynchronous trap!
It's very unintuitive for something like img = loadImage("myPic.jpg"); image(img, 0, 0); to fail.

Yeah, well, that's **not a very difficult lesson** to learn either. And it's pretty useful. If only Processing provided the **next step** to go (the solution to that problem, which is the asynchronous programming paradigm), but it doesn't because Processing's creators think people of "_the artist category [...]"_ are too stupid to jump to the next level.

That reminds me of an another bug/feature request I opened in Processing asking to change parseInt(string, int) to take a radix as a second parameter just like Java's Integer.parseInt() *and* JavaScript's parseInt(). Ben Fry replied that (I quote, this is hilarious)  _"a vast majority of our audience has no idea what 'radix' is"_. Again, they **treat their audience as too stupid** to understand (or even to be wanting to learn) such concepts as a radix.

Pretty sad for a language that presents itself as *a language for learning how to code*.

**Comment by GoToLoop** [comment]
> Again, they treat their audience as too stupid to understand (or even to be wanting to learn) such concepts as a radix.

Fry resists any changes to his API to the extreme. Ignores all voices of reason. Quickly loses his short temper then close & lock the thread!

Just 8 hours ago he's locked @Pomax 's thread up: https://github.com/processing/processing/issues/4328#event-653774720

I was the last commenter, arguing that **size()**'s 3rd parameter can normally use a variable, unlike 1st & 2nd, and it gets successfully picked up by PDE's pre-processor.

He's just ignored, pasted some link about P3's changes, claiming it would explain everything at length.
But of course, there's nothing there about the 3rd parameter. And the reason why it's unaffected!
And mainly, why the same "feature" couldn't be extended for the 1st & 2nd parameters.  :P  

I've also tried to bring some tiny changes to Processing's API, both there and even here in Pjs and also p5.js.  But alas, they were all refuted and locked up!  :rage:

**Comment by LujunWeng** [comment]
At least, the official website should be updated to announce that. p5js now has not a very good support of 3d. So I turned to use processing.js and it took me some time to figure out why I could not draw anything.

**Comment by GoToLoop** [comment]
Indeed Pjs still got the upper hand on WebGL performance. p5.js is getting there. Dunno when.  :watch:

**Comment by dderiso** [comment]
@LujunWeng If the main issue is a lack of a draw function, here is an alternative. Simply create a function called "draw" and put whatever you want to render inside. Now, at each time step, you can explicitly call the draw function using javascript's built in ```window.setInterval(draw, 1000/10);``` function by specifying ```draw``` as the target function as shown. Hope this helps! (PS. I was also confused by this)

**Comment by LujunWeng** [comment]
@dderiso Thank you for this. I had solved it. The 1.4.8 version works well. I just hope that there would be a notice or something so that other people do not have to waste time to figure out what is going wrong.

**Comment by GoToLoop** [comment]
@LujunWeng, aFaIK, no changes were made to WebGL since version 1.4.1.
Actually no meaningful progress was made since 1.4.1!
Any version 1.4.1 and up we pick won't make much difference.  :sleeping:

**Comment by Pomax** [comment]
what do you mean "almost"? That's pretty much where it was before 99% of the devs all graduated at the same time and left for different projects. If you're unhappy with where Pjs is, feel free to jump in and help get it to Processing 3.0 compat, but commenting on almost every issue that Pjs is so out of date with frowning smileys is not being helpful. We get it, you're unhappy: please either help start fixing it, or stop hating on a project that literally **has no one working on it**.

This ticket was filed because the docs do not mention that the API-only library was discontinued. Which is true, and has been opened over on https://github.com/processing-js/processing-js.github.io/issues/29
