### ISSUE TITLE
random(low, high) can return high.

### ISSUE THREAD

**Issue by lgto4** [processing-js/processing-js#244]
Due to the default behavior of the floating point unit sometimes rounding upward, `random(low, high)` can return `high` when the interval `low .. high` is sufficiently small.  Simply retrying in that case neither invalidates the uniformity of the resulting numbers, nor will it take very long (probabilistically) to produce a valid result.

The proposed fixed with assertion checking can be found [here](https://www.khanacademy.org/computer-programming/a-modest-random-proposal/6185331072)

**Comment by Pomax** [comment]
could I request you make that a PR, so comments can be left per line? The fix would be against https://github.com/processing-js/processing-js/blob/master/src/P5Functions/Math.js#L428

**Comment by lgto4** [comment]
This is my fear about open source in general.  I have no idea what a PR is, or how to discover how to make one.  (And there are plenty of other fools like me who have no fear.)  I'm willing to learn though.

**Comment by Pomax** [comment]
it's a "pull request", it's what lets github merge changes that someone else makes into the main code. It's actually relatively easy to do if you already wrote the code: if you go to https://github.com/processing-js/processing-js/blob/master/src/P5Functions/Math.js and click the "edit" icon on the upper right of the file's pane, then you get to edit the file and put your changes in, then all the way at the bottom of the page you can write a summary for the changes you made and then commit the changes. This will create a copy of the file under your own account, and then you can tell github to form a pull request, so that there is now a request to merge your changes into this respository's code.

**Comment by lgto4** [comment]
Ok.  As you can see I did it.  I have no idea where my changes went, so it's not like I've tested my final keystrokes.

**Comment by Pomax** [comment]
it's in https://github.com/lgto4/processing-js/tree/patch-1, so if you go to that link and click "new pull request", you can then form a PR against `processing-js/processing-js` (there's a lot of forks, so making sure that's the one it's requesting a merge against is fairly crucial)

**Comment by lgto4** [comment]
I believe that I did a new pull request, but I have heard nothing since. Is all well?

**Comment by Pomax** [comment]
sorry, just got back from an all-company week-long meeting and catching up on work from that, I'll probably have time to revisit this the coming weekend but not before. (lots of PRs/reviews to catch up on)

**Comment by lgto4** [comment]
No problem...  I was just wondering if my actions took...

**Comment by atgeflu** [comment]
@lgto4: Thanks for pointing this out. 
This looks like a really interesting problem.
I was wondering whether it was a specific Processing.js problem or whether the original Processing and new P5.js where also affected.
I was able to recreate the problem on all 3 platforms so I guess they're all affected. 
I guess I'll go ahead and open issues for the other 2 projects as well, so they can consider fixing it too.

**Comment by GoToLoop** [comment]
There was something related to **random()**'s precision here: https://github.com/Khan/live-editor/issues/432
Back then I've suggested a new **randomStrict()** function in order to keep the original behavior across Processing's spin-offs and also for performance reasons.

**Comment by lgto4** [comment]
@GoToLoop Thanks.  I can see that the Khan live-editor discussion is related, but I cannot get the gist of it.  That is partially because the discussion starts with "random(a,b) returns a number
in the half open interval (a,b]" which is false.  Had the statement complained about the interval [a, b] then it would have been accurate and the same as this complaint.

**Comment by Pomax** [comment]
Just to get clarity, is there a pair of numbers that can be input to random (and thus its unit test) that can be passed in to show a failing test on the current code, but passing test on the proposed PR?

**Comment by lgto4** [comment]
Yes, but only probabilistically.  The following never passes on my Chrome of Firefox browsers: ```var center = 512;
var delta = 1/1000/1000/100;
var a, b, i, r, pass = true;
for (i = 0; i < 10000000; i++) {
    /* Ascending interval */
    a = center - delta;
    b = center;
    r = random(a, b);
    if (r >= b || r < a) {
        pass = false;
        println("On iteration " + i + ", " + r + " is not in the interval [ " + a + ", " + b + " ).");
        break;
    }
}
for (; i < 20000000; i++) {
    /* Descending interval */
    a = center + delta;
    b = center;
    r = random(a, b);
    if (r <= b || r > a) {
        pass = false;
        println("On iteration " + i + ", " + r + " is not in the interval [ " + a + ", " + b + " ).");
        break;
    }
}
println(pass ? "Passed." : "Failed!");``` My proposed fix always passes.

**Comment by Pomax** [comment]
Probabilistic is fine, we can simply run things 10k times. As part of the unit test in `./test/unit/random.pde`, we can rewrite this to:
```
var r,
    c = 512,
    d = 0.000000001,
    a = center - delta,
    b = c,
    failed = false;
for (var i=0; i<10000; i++) {
  r = random(a, b);
  if (r >= b || r < a) {
    failed = true;
    break;
  }
}
// at this point `failed` reflects whether or not the previous run failed even once.
_checkFalse(failed);
```

**Comment by lgto4** [comment]
I edited `./test/unit/random.pde`, after correcting "center" and "delta" and upping the loop limit such that when I tested the test, it caught the problem 90% of the time. 

Should we be concerned that the test is Javascript when the rest of the file appears to be Java?

I don't know if I am supposed to update some pull request.  My page header says "Pull requests 0".

**Comment by Pomax** [comment]
No real difference, although making it "proper" processing's a good point - that `var r` should probably be `float r`, and `for(var i` should be `for(int i` (Pjs technically throws the type information away, but it's good to keep unit tests loadable in the pde, good point)

Did you edit the test/unit/random.pde in the same branch as your pull request, or as a new branch?

**Comment by lgto4** [comment]
Yes, I believe that all my edits are in the same branch.

**Comment by Pomax** [comment]
hmm, that's curious... does the code in https://github.com/processing-js/processing-js/pull/245/files reflect what it should be? If not, does it show correctly on your repository/branch if you load its url?

**Comment by lgto4** [comment]
When I click on [https://github.com/processing-js/processing-js/pull/245/files] it shows the deltas of the two files that I edited - src/P5Functions/Math.js and test/unit/random.pde .

**Comment by Pomax** [comment]
I guess if the deltas look right we can chuck the odd git notice up to "git just being obtuse". It does that every now and then, unfortunately.

**Comment by Pomax** [comment]
merged https://github.com/processing-js/processing-js/pull/245

**Comment by lgto4** [comment]
Thanks for the merge!

While I am no longer a github virgin, I'm still wondering how it all works and I still await gratification.

**Comment by Pomax** [comment]
v1.6.0 should now be on npm/bower -- what parts of the git process can I still help impart gratification on?

**Comment by lgto4** [comment]
Well, I don't know what a npm/bower is, but  I assume it's good.

What I want to do is edit a file and then build the entire Processing.js "package" so that I can test it and run all the prepackaged tests against it. 

I remain mystified as to how I find the root of any fork that I may have made.  (I managed to get by (git by?) by clicking on links in email from you.)

**Comment by Pomax** [comment]
npm is the package manager that is bundled with nodejs, and a de facto JS library distribution system (both for "server-side" javascript libraries and "client-side" libraries, although the line's a bit blurred there in recent years, as a lot of server side code can be bundled for client side use without much effort).

For the "full blown" development expererience, the steps are a bit more involved: there are two options, one is the command line `git` client, the other a GUI client. In both cases you would fork this project so that you have a "local to your username" copy (which you already have over on https://github.com/lgto4/processing-js), and then you would clone this repository (which takes a bit because it has a lot of commit history it will pull down to your local machine) to your local machine,

You can then do the branch administration locally (creating new branches and switching between branches), and modify files as necessary, then sync them back to github (any work you do locally that  you'd like reflected on github needs to be synced - for work you do on your local copy that you want to sync back to your personal github fork you use `commit` operations and `push` operations, the first marks file changes as "I actually want these things synced" and the latter being the actual sync command), and for any work you've synced to your personal fork that you want to have merged back into the master repository you file pull requests, similar to what you've already do for this particular fix.

Github themselves have some good tutorials on this over on their "github guides" site, so reading through https://guides.github.com/activities/hello-world/ is a good way to get familiar with both the terminology and the steps involved.

**Comment by lgto4** [comment]
Guess what?  `random(b)` can return `b`.  Do we want a new bug report or to continue to flog this bug report?

**Comment by GoToLoop** [comment]
My opinion stays the same: it's better to create a new name for such stricter method and keep the original behavior around. It's very clear by now that it's a native float type behavior which JS & Java share alike.

**Comment by Pomax** [comment]
Looking at the official docs, "For example, random(5) returns values between 0 and 5 (starting at zero, and up to, but not including, 5)." so yeah if `random(x)` can yield `x` then that should be a new issue.
