### ISSUE TITLE
Is PShader implemented? If not, are there plans to implement it?

### ISSUE THREAD

**Issue by JetStarBlues** [processing-js/processing-js#249]
See https://processing.org/tutorials/pshader/

Websites like www.shadertoy.com convince me it is possible.

**Comment by Pomax** [comment]
It is not, and there no devs currently active on this project so if you can find someone who might be willing to take a stab at this, then great! But if not, this will likely not be happening any time soon, unfortunately.

**Comment by JetStarBlues** [comment]
Ok sounds good. I saw on the P5.js repo that they're working on support for shaders, so all hope's not lost.

**Comment by Pomax** [comment]
indeed. I'm a little unclear what the true relationship is between P5 and P5.js, since the syntax is not the same (p5.js being a 'what if processing was imagined today' project) but if they cover parts that Pjs doesn't (or in this case due to no active developers, can't) then that's fantastic news for people who need those parts.

I'll close this issue, but if you (or someone you know) feel(s) like adding this to Pjs, please do open an issue for that work and I'll be more than happy to act as Pjs reviewer.
