### ISSUE TITLE
random unit test fails on master

### ISSUE THREAD

**Issue by Pomax** [processing-js/processing-js#267]
pretty sure we tested this when the random fixes were landed, but I see the unit test for `random` failing consistently.
```
   [random.pde/4] true != false

    [one or more tests failed]
    random.pde failed (1 times)
```

**Comment by CapacitorSet** [comment]
This happens because the test suite does not match the expected behaviour.

The official documentation states that

>If only one parameter is passed to the function, it will return a float between zero and the value of the `high` parameter.

It could be interpreted as either "zero, `high`, or any value inbetween" or "any value between zero and `high`, but not the extremes"; however, the library tests for "any value between zero and `high`, including zero, but not `high`". I'll push a fix in minutes.
